version: '2.1'

services:
  atom:
    build: .
    container_name: atom
    volumes:
      - "data_work:/home/ubuntu/work"
    restart: always
    ports:
      - "22:22"
    network_mode: "host"

volumes:
  data_work:
