version: '2.1'

services:
  atom:
    build: .
    image: atom
    container_name: atom
    volumes:
      - "data_work:/home/ubuntu/work"
    restart: always
    ports:
      - "22:22"
      - "5901:5901"
    network_mode: "host"

volumes:
  data_work:
